# Generated by Django 3.2 on 2022-09-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktype', models.IntegerField(default=0)),
                ('choices', models.CharField(default='hogehoge', max_length=256)),
                ('answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='description',
            field=models.CharField(default='hogehoge', max_length=256),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='name',
            field=models.CharField(default='hogehoeg', max_length=64),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='reward',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
