# Generated by Django 3.2 on 2022-09-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_task_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
