# Generated by Django 3.2 on 2022-09-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_tasksmodel_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tasksmodel'),
        ),
    ]
