# Generated by Django 3.2 on 2022-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_taskmodel_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='tasksmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tasksmodel',
            name='size',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='belong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='key',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
