# Generated by Django 3.2 on 2022-10-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20221006_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='choices',
            new_name='content',
        ),
    ]
