# Generated by Django 3.2 on 2022-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_choices_taskmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='userid1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='userid2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tasksmodel',
            name='userid3',
            field=models.IntegerField(null=True),
        ),
    ]
